
# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

# BEGIN AUTO-ADDED BY MCUXPRESSO EXTENSION 20/02/2026 15:48
CONFIG_MCUX_COMPONENT_driver.edma_soc=y
CONFIG_MCUX_COMPONENT_driver.ctimer=y
CONFIG_MCUX_COMPONENT_driver.edma4=y
CONFIG_MCUX_COMPONENT_driver.flexio=y
CONFIG_MCUX_COMPONENT_driver.flexio_spi_edma=y
CONFIG_MCUX_COMPONENT_driver.flexio_spi=y
CONFIG_SPI_RETRY_TIMES=0
CONFIG_MCUX_COMPONENT_driver.flexio_i2c_master=y
CONFIG_I2C_RETRY_TIMES=0
CONFIG_MCUX_COMPONENT_driver.inputmux=y
CONFIG_MCUX_COMPONENT_driver.lpadc=y
CONFIG_LPADC_CONVERSION_COMPLETE_TIMEOUT=0
CONFIG_LPADC_CALIBRATION_READY_TIMEOUT=0
CONFIG_LPADC_GAIN_CAL_READY_TIMEOUT=0
CONFIG_MCUX_COMPONENT_driver.pwm=y
CONFIG_MCUX_COMPONENT_driver.qdc=y
CONFIG_MCUX_COMPONENT_driver.utick=y
CONFIG_MCUX_COMPONENT_driver.vref_1=y
CONFIG_MCUX_COMPONENT_middleware.fmstr=y
CONFIG_MCUX_COMPONENT_middleware.fmstr.platform_gen32le=y
CONFIG_MCUX_PRJSEG_middleware.fmstr.generated_config=n
CONFIG_MCUX_COMPONENT_middleware.rtcesl.cm33f=y
CONFIG_MCUX_PRJSEG_module.board.use_board_clock=n
CONFIG_MCUX_PRJSEG_module.board.clock=n
CONFIG_MCUX_HAS_PRJSEG_module.board.pinmux_sel=n
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_folder=n
# END AUTO-ADDED BY MCUXPRESSO EXTENSION


# BEGIN AUTO-ADDED BY MCUXPRESSO EXTENSION 22/02/2026 00:28
CONFIG_MCUX_PRJSEG_module.board.use_board_clock=y
CONFIG_MCUX_PRJSEG_module.board.clock_customize_folder=y
CONFIG_MCUX_HAS_PRJSEG_module.board.pinmux_sel=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_customize_folder=y
CONFIG_MCUX_PRJSEG_project.hw_app_project_folder=y
CONFIG_MCUX_PRJSEG_module.board.boardfile=n
CONFIG_MCUX_PRJSEG_project.hw_app_project_core_folder=y
# END AUTO-ADDED BY MCUXPRESSO EXTENSION

# BEGIN AUTO-ADDED BY MCUXPRESSO EXTENSION 22/02/2026 01:05
CONFIG_MCUX_HAS_PRJSEG_project.use_hw_app=n
CONFIG_MCUX_PRJSEG_project.hw_app_project_core_folder=n
# END AUTO-ADDED BY MCUXPRESSO EXTENSION

# BEGIN AUTO-ADDED BY MCUXPRESSO EXTENSION 22/02/2026 01:07
CONFIG_MCUX_PRJSEG_module.board.use_board_clock=n
CONFIG_MCUX_PRJSEG_module.board.clock_customize_folder=n
CONFIG_MCUX_HAS_PRJSEG_module.board.pinmux_sel=n
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_folder=n
# END AUTO-ADDED BY MCUXPRESSO EXTENSION

# BEGIN AUTO-ADDED BY MCUXPRESSO EXTENSION 18/03/2026 23:08
CONFIG_MCUX_COMPONENT_driver.lpflexcomm_lpi2c=y
CONFIG_MCUX_COMPONENT_driver.lpflexcomm_lpi2c_edma=y
CONFIG_MCUX_COMPONENT_driver.mailbox=y
CONFIG_MCUX_COMPONENT_driver.sema42=y
CONFIG_SEMA42_BUSY_POLL_COUNT=0
# END AUTO-ADDED BY MCUXPRESSO EXTENSION

# BEGIN AUTO-ADDED BY MCUXPRESSO EXTENSION 20/03/2026 00:35
CONFIG_MCUX_COMPONENT_driver.lptmr=y
# END AUTO-ADDED BY MCUXPRESSO EXTENSION

# BEGIN AUTO-ADDED BY MCUXPRESSO EXTENSION 21/03/2026 16:41
CONFIG_MCUX_COMPONENT_driver.lptmr=y
# END AUTO-ADDED BY MCUXPRESSO EXTENSION
