/*
 * Copyright 2026 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MCXN947
package_id: MCXN947VDF
mcu_data: ksdk2_0
processor_version: 25.12.10
board: FRDM-MCXN947
expansion_headers:
- id: lpc_style_arduino
  name: Arduino
  connectors:
  - {id: C1, name: C1}
  - {id: C2, name: C2}
  - {id: C3, name: C3}
  - {id: C4, name: C4}
pin_labels:
- {pin_num: K1, pin_signal: PIO2_5/TRIG_OUT3/FC9_P2/SDHC0_CMD/SCT0_OUT3/PWM1_B1/FLEXIO0_D13/SMARTDMA_PIO25/FLEXSPI0_B_DATA1/SINC0_MBIT1/SAI0_TXD1, label: M1_INB,
  identifier: M1_INB}
- {pin_num: P1, pin_signal: PIO4_0/WUU0_IN18/TRIG_IN6/FC2_P0/CT_INP16/SMARTDMA_PIO24/PLU_IN0/SINC0_MCLK3, label: 'P4_0/J8[4]/SJ14[1]', identifier: PIXY_SDO;PIXY_SDA;PIXY_SCL}
- {pin_num: K2, pin_signal: PIO2_6/TRIG_IN4/FC9_P4/SDHC0_D3/SCT0_OUT4/PWM1_A0/FLEXIO0_D14/SMARTDMA_PIO26/FLEXSPI0_B_DATA2/SINC0_MCLK2/SAI0_TX_BCLK, label: M1_PWM,
  identifier: M1_PWM}
- {pin_num: L2, pin_signal: PIO2_7/TRIG_IN5/FC9_P5/SDHC0_D2/SCT0_OUT5/PWM1_B0/FLEXIO0_D15/SMARTDMA_PIO27/FLEXSPI0_B_DATA3/SINC0_MBIT2/SAI0_TX_FS, label: M1_INA, identifier: M1_INA}
- {pin_num: P2, pin_signal: PIO4_1/TRIG_IN7/FC2_P1/CT_INP17/SMARTDMA_PIO25/PLU_IN1, label: 'P4_1/J8[3]/SJ15[1]', identifier: PIXY_SCK;PIXY_SDA;PIXY_SCL}
- {pin_num: H3, pin_signal: PIO2_2/WUU0_IN16/CLKOUT/FC9_P3/SDHC0_D1/SCT0_OUT0/PWM1_A2/FLEXIO0_D10/SMARTDMA_PIO22/FLEXSPI0_B_SS0_b/SINC0_MCLK0/SAI0_TXD0, label: M2_INB,
  identifier: M2_INB}
- {pin_num: J3, pin_signal: PIO2_3/FC9_P1/SDHC0_D0/SCT0_OUT1/PWM1_B2/FLEXIO0_D11/SMARTDMA_PIO23/FLEXSPI0_B_SCLK/SINC0_MBIT0/SAI0_RXD0, label: M2_INA, identifier: M2_INA}
- {pin_num: K3, pin_signal: PIO2_4/WUU0_IN17/FC9_P0/SDHC0_CLK/SCT0_OUT2/PWM1_A1/FLEXIO0_D12/SMARTDMA_PIO24/FLEXSPI0_B_DATA0/SINC0_MCLK1/SAI0_RXD1, label: M2_PWM,
  identifier: M2_PWM}
- {pin_num: L5, pin_signal: PIO1_21/TRIG_OUT2/FC5_P5/FC4_P1/CT3_MAT3/SCT0_OUT9/FLEXIO0_D29/SMARTDMA_PIO17/PLU_OUT7/ENET0_MDIO/SAI1_MCLK/CAN1_RXD/ADC1_A21/CMP2_IN3,
  label: 'P1_21/SJ3[1]/J1[7]', identifier: M1_INA}
- {pin_num: B6, pin_signal: PIO0_24/FC1_P0/CT0_MAT0/ADC0_B16, label: 'P0_24/SJ7[1]', identifier: BATTERY_PIN;VDCB}
- {pin_num: T7, pin_signal: PIO4_13/TRIG_IN8/FC2_P1/USB1_ID/CT4_MAT1/FLEXIO0_D21/PLU_OUT1/SINC0_MBIT0/CAN0_TXD/OPAMP0_INP1/ADC0_B5/ADC1_B5, label: 'P4_13/SJ10[1]/SJ2[3]/J8[18]',
  identifier: M2_INA}
- {pin_num: F10, pin_signal: PIO0_26/FC1_P2/CT0_MAT2/ADC0_B18, label: 'P0_26/J2[10]', identifier: BUTTON_CLICK}
- {pin_num: E11, pin_signal: PIO0_14/FC1_P6/FC0_P2/CT_INP2/UTICK_CAP0/FLEXIO0_D6/ADC0_B14, label: RC_1, identifier: SERVO;RC_1;RC_1_RISE;RC_1_FALL}
- {pin_num: M12, pin_signal: PIO5_4/TRIG_OUT7/SPC_LPREQ/TAMPER2/ADC1_B12, label: 'P5_4/J2[7]', identifier: VDCB}
- {pin_num: G13, pin_signal: PIO0_15/FC0_P3/CT_INP3/UTICK_CAP1/FLEXIO0_D7/ADC0_B15, label: RC_2, identifier: RC_2;RC_2_RISE;RC_2_FALL}
- {pin_num: J15, pin_signal: PIO3_16/FC8_P2/CT_INP8/PWM1_A2/FLEXIO0_D24/SMARTDMA_PIO16/SIM0_CLK/SAI1_TX_BCLK, label: 'P3_16/SJ11[1]', identifier: M2_INB}
- {pin_num: K17, pin_signal: PIO3_19/FC7_P6/CT2_MAT1/PWM1_X1/FLEXIO0_D27/SMARTDMA_PIO19/SAI1_RX_FS, label: 'P3_19/J5[1]/J1[13]', identifier: SERVO}
- {pin_num: M17, pin_signal: PIO3_20/WUU0_IN27/TRIG_OUT0/FC8_P4/FC6_P0/CT2_MAT2/PWM1_A3/FLEXIO0_D28/SMARTDMA_PIO20/SIM0_PD/SAI1_TXD0, label: 'P3_20/J6[6]/J1[5]',
  identifier: M1_INB}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "fsl_inputmux.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitDEBUG_UARTPins();
    BOARD_InitSWD_DEBUGPins();
    BOARD_InitLEDsPins();
    BOARD_InitBUTTONsPins();
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitDEBUG_UARTPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: A1, peripheral: LP_FLEXCOMM4, signal: LPFLEXCOMM_P0, pin_signal: PIO1_8/WUU0_IN10/LPTMR1_ALT3/TRACE_DATA0/FC4_P0/FC5_P4/CT_INP8/SCT0_OUT2/FLEXIO0_D16/SMARTDMA_PIO4/PLU_OUT0/ENET0_TXD2/I3C1_SDA/TSI0_CH17/ADC1_A8,
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, passive_filter: disable, pull_value: low, input_buffer: enable,
    invert_input: normal}
  - {pin_num: B1, peripheral: LP_FLEXCOMM4, signal: LPFLEXCOMM_P1, pin_signal: PIO1_9/TRACE_DATA1/FC4_P1/FC5_P5/CT_INP9/SCT0_OUT3/FLEXIO0_D17/SMARTDMA_PIO5/PLU_OUT1/ENET0_TXD3/I3C1_SCL/TSI0_CH18/ADC1_A9,
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, passive_filter: disable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDEBUG_UARTPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitDEBUG_UARTPins(void)
{
    /* Enables the clock for PORT1: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port1);

    const port_pin_config_t DEBUG_UART_RX = {/* Internal pull-up/down resistor is disabled */
                                             .pullSelect = kPORT_PullDisable,
                                             /* Low internal pull resistor value is selected. */
                                             .pullValueSelect = kPORT_LowPullResistor,
                                             /* Fast slew rate is configured */
                                             .slewRate = kPORT_FastSlewRate,
                                             /* Passive input filter is disabled */
                                             .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                             /* Open drain output is disabled */
                                             .openDrainEnable = kPORT_OpenDrainDisable,
                                             /* Low drive strength is configured */
                                             .driveStrength = kPORT_LowDriveStrength,
                                             /* Pin is configured as FC4_P0 */
                                             .mux = kPORT_MuxAlt2,
                                             /* Digital input enabled */
                                             .inputBuffer = kPORT_InputBufferEnable,
                                             /* Digital input is not inverted */
                                             .invertInput = kPORT_InputNormal,
                                             /* Pin Control Register fields [15:0] are not locked */
                                             .lockRegister = kPORT_UnlockRegister};
    /* PORT1_8 (pin A1) is configured as FC4_P0 */
    PORT_SetPinConfig(BOARD_INITDEBUG_UARTPINS_DEBUG_UART_RX_PORT, BOARD_INITDEBUG_UARTPINS_DEBUG_UART_RX_PIN, &DEBUG_UART_RX);

    const port_pin_config_t DEBUG_UART_TX = {/* Internal pull-up/down resistor is disabled */
                                             .pullSelect = kPORT_PullDisable,
                                             /* Low internal pull resistor value is selected. */
                                             .pullValueSelect = kPORT_LowPullResistor,
                                             /* Fast slew rate is configured */
                                             .slewRate = kPORT_FastSlewRate,
                                             /* Passive input filter is disabled */
                                             .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                             /* Open drain output is disabled */
                                             .openDrainEnable = kPORT_OpenDrainDisable,
                                             /* Low drive strength is configured */
                                             .driveStrength = kPORT_LowDriveStrength,
                                             /* Pin is configured as FC4_P1 */
                                             .mux = kPORT_MuxAlt2,
                                             /* Digital input enabled */
                                             .inputBuffer = kPORT_InputBufferEnable,
                                             /* Digital input is not inverted */
                                             .invertInput = kPORT_InputNormal,
                                             /* Pin Control Register fields [15:0] are not locked */
                                             .lockRegister = kPORT_UnlockRegister};
    /* PORT1_9 (pin B1) is configured as FC4_P1 */
    PORT_SetPinConfig(BOARD_INITDEBUG_UARTPINS_DEBUG_UART_TX_PORT, BOARD_INITDEBUG_UARTPINS_DEBUG_UART_TX_PIN, &DEBUG_UART_TX);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitSWD_DEBUGPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: A16, peripheral: SWD, signal: SWCLK, pin_signal: PIO0_1/TCLK/SWCLK/FC1_P1/CT_INP1, slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down,
    pull_enable: enable, input_buffer: enable, invert_input: normal}
  - {pin_num: A17, peripheral: SWD, signal: SWDIO, pin_signal: PIO0_0/TMS/SWDIO/FC1_P0/CT_INP0, slew_rate: fast, open_drain: disable, drive_strength: high, pull_select: up,
    pull_enable: enable, input_buffer: enable, invert_input: normal}
  - {pin_num: B16, peripheral: SWD, signal: SWO, pin_signal: PIO0_2/TDO/SWO/FC1_P2/CT0_MAT0/UTICK_CAP0/I3C0_PUR, slew_rate: fast, open_drain: disable, drive_strength: high,
    pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitSWD_DEBUGPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitSWD_DEBUGPins(void)
{
    /* Enables the clock for PORT0 controller: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port0);

    const port_pin_config_t DEBUG_SWD_SWDIO = {/* Internal pull-up resistor is enabled */
                                               .pullSelect = kPORT_PullUp,
                                               /* Low internal pull resistor value is selected. */
                                               .pullValueSelect = kPORT_LowPullResistor,
                                               /* Fast slew rate is configured */
                                               .slewRate = kPORT_FastSlewRate,
                                               /* Passive input filter is disabled */
                                               .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                               /* Open drain output is disabled */
                                               .openDrainEnable = kPORT_OpenDrainDisable,
                                               /* High drive strength is configured */
                                               .driveStrength = kPORT_HighDriveStrength,
                                               /* Pin is configured as SWDIO */
                                               .mux = kPORT_MuxAlt1,
                                               /* Digital input enabled */
                                               .inputBuffer = kPORT_InputBufferEnable,
                                               /* Digital input is not inverted */
                                               .invertInput = kPORT_InputNormal,
                                               /* Pin Control Register fields [15:0] are not locked */
                                               .lockRegister = kPORT_UnlockRegister};
    /* PORT0_0 (pin A17) is configured as SWDIO */
    PORT_SetPinConfig(BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDIO_PORT, BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDIO_PIN, &DEBUG_SWD_SWDIO);

    const port_pin_config_t DEBUG_SWD_SWDCLK = {/* Internal pull-down resistor is enabled */
                                                .pullSelect = kPORT_PullDown,
                                                /* Low internal pull resistor value is selected. */
                                                .pullValueSelect = kPORT_LowPullResistor,
                                                /* Fast slew rate is configured */
                                                .slewRate = kPORT_FastSlewRate,
                                                /* Passive input filter is disabled */
                                                .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                                /* Open drain output is disabled */
                                                .openDrainEnable = kPORT_OpenDrainDisable,
                                                /* Low drive strength is configured */
                                                .driveStrength = kPORT_LowDriveStrength,
                                                /* Pin is configured as SWCLK */
                                                .mux = kPORT_MuxAlt1,
                                                /* Digital input enabled */
                                                .inputBuffer = kPORT_InputBufferEnable,
                                                /* Digital input is not inverted */
                                                .invertInput = kPORT_InputNormal,
                                                /* Pin Control Register fields [15:0] are not locked */
                                                .lockRegister = kPORT_UnlockRegister};
    /* PORT0_1 (pin A16) is configured as SWCLK */
    PORT_SetPinConfig(BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDCLK_PORT, BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDCLK_PIN, &DEBUG_SWD_SWDCLK);

    const port_pin_config_t DEBUG_SWD_SWO = {/* Internal pull-up/down resistor is disabled */
                                             .pullSelect = kPORT_PullDisable,
                                             /* Low internal pull resistor value is selected. */
                                             .pullValueSelect = kPORT_LowPullResistor,
                                             /* Fast slew rate is configured */
                                             .slewRate = kPORT_FastSlewRate,
                                             /* Passive input filter is disabled */
                                             .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                             /* Open drain output is disabled */
                                             .openDrainEnable = kPORT_OpenDrainDisable,
                                             /* High drive strength is configured */
                                             .driveStrength = kPORT_HighDriveStrength,
                                             /* Pin is configured as SWO */
                                             .mux = kPORT_MuxAlt1,
                                             /* Digital input enabled */
                                             .inputBuffer = kPORT_InputBufferEnable,
                                             /* Digital input is not inverted */
                                             .invertInput = kPORT_InputNormal,
                                             /* Pin Control Register fields [15:0] are not locked */
                                             .lockRegister = kPORT_UnlockRegister};
    /* PORT0_2 (pin B16) is configured as SWO */
    PORT_SetPinConfig(BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWO_PORT, BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWO_PIN, &DEBUG_SWD_SWO);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLEDsPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: C4, peripheral: GPIO1, signal: 'GPIO, 2', pin_signal: PIO1_2/TRIG_OUT0/FC3_P2/FC4_P6/CT1_MAT0/SCT0_IN6/FLEXIO0_D10/ENET0_MDC/SAI1_TXD0/CAN0_TXD/TSI0_CH2/ADC0_A18/CMP2_IN0,
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: B12, peripheral: GPIO0, signal: 'GPIO, 10', pin_signal: PIO0_10/FC0_P6/CT0_MAT0/FLEXIO0_D2/ADC0_B10, slew_rate: fast, open_drain: disable, drive_strength: low,
    pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: E10, peripheral: GPIO0, signal: 'GPIO, 27', pin_signal: PIO0_27/FC1_P3/CT0_MAT3/ADC0_B19, slew_rate: fast, open_drain: disable, drive_strength: low,
    pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLEDsPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitLEDsPins(void)
{
    /* Enables the clock for PORT0 controller: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port0);
    /* Enables the clock for PORT1: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port1);

    const port_pin_config_t LED_RED = {/* Internal pull-up/down resistor is disabled */
                                       .pullSelect = kPORT_PullDisable,
                                       /* Low internal pull resistor value is selected. */
                                       .pullValueSelect = kPORT_LowPullResistor,
                                       /* Fast slew rate is configured */
                                       .slewRate = kPORT_FastSlewRate,
                                       /* Passive input filter is disabled */
                                       .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                       /* Open drain output is disabled */
                                       .openDrainEnable = kPORT_OpenDrainDisable,
                                       /* Low drive strength is configured */
                                       .driveStrength = kPORT_LowDriveStrength,
                                       /* Pin is configured as PIO0_10 */
                                       .mux = kPORT_MuxAlt0,
                                       /* Digital input enabled */
                                       .inputBuffer = kPORT_InputBufferEnable,
                                       /* Digital input is not inverted */
                                       .invertInput = kPORT_InputNormal,
                                       /* Pin Control Register fields [15:0] are not locked */
                                       .lockRegister = kPORT_UnlockRegister};
    /* PORT0_10 (pin B12) is configured as PIO0_10 */
    PORT_SetPinConfig(BOARD_INITLEDSPINS_LED_RED_PORT, BOARD_INITLEDSPINS_LED_RED_PIN, &LED_RED);

    const port_pin_config_t LED_GREEN = {/* Internal pull-up/down resistor is disabled */
                                         .pullSelect = kPORT_PullDisable,
                                         /* Low internal pull resistor value is selected. */
                                         .pullValueSelect = kPORT_LowPullResistor,
                                         /* Fast slew rate is configured */
                                         .slewRate = kPORT_FastSlewRate,
                                         /* Passive input filter is disabled */
                                         .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                         /* Open drain output is disabled */
                                         .openDrainEnable = kPORT_OpenDrainDisable,
                                         /* Low drive strength is configured */
                                         .driveStrength = kPORT_LowDriveStrength,
                                         /* Pin is configured as PIO0_27 */
                                         .mux = kPORT_MuxAlt0,
                                         /* Digital input enabled */
                                         .inputBuffer = kPORT_InputBufferEnable,
                                         /* Digital input is not inverted */
                                         .invertInput = kPORT_InputNormal,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         .lockRegister = kPORT_UnlockRegister};
    /* PORT0_27 (pin E10) is configured as PIO0_27 */
    PORT_SetPinConfig(BOARD_INITLEDSPINS_LED_GREEN_PORT, BOARD_INITLEDSPINS_LED_GREEN_PIN, &LED_GREEN);

    const port_pin_config_t LED_BLUE = {/* Internal pull-up/down resistor is disabled */
                                        .pullSelect = kPORT_PullDisable,
                                        /* Low internal pull resistor value is selected. */
                                        .pullValueSelect = kPORT_LowPullResistor,
                                        /* Fast slew rate is configured */
                                        .slewRate = kPORT_FastSlewRate,
                                        /* Passive input filter is disabled */
                                        .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                        /* Open drain output is disabled */
                                        .openDrainEnable = kPORT_OpenDrainDisable,
                                        /* Low drive strength is configured */
                                        .driveStrength = kPORT_LowDriveStrength,
                                        /* Pin is configured as PIO1_2 */
                                        .mux = kPORT_MuxAlt0,
                                        /* Digital input enabled */
                                        .inputBuffer = kPORT_InputBufferEnable,
                                        /* Digital input is not inverted */
                                        .invertInput = kPORT_InputNormal,
                                        /* Pin Control Register fields [15:0] are not locked */
                                        .lockRegister = kPORT_UnlockRegister};
    /* PORT1_2 (pin C4) is configured as PIO1_2 */
    PORT_SetPinConfig(BOARD_INITLEDSPINS_LED_BLUE_PORT, BOARD_INITLEDSPINS_LED_BLUE_PIN, &LED_BLUE);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitBUTTONsPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: C14, peripheral: GPIO0, signal: 'GPIO, 6', pin_signal: PIO0_6/ISPMODE_N/FC0_P2/FC1_P6/CT_INP2/HSCMP2_OUT/PDM0_DATA1/TSI0_CH10, slew_rate: fast, open_drain: disable,
    drive_strength: low, pull_select: up, pull_enable: enable, input_buffer: enable, invert_input: normal}
  - {pin_num: B7, peripheral: GPIO0, signal: 'GPIO, 23', pin_signal: PIO0_23/WUU0_IN5/EWM0_OUT_b/FC1_P3/CT_INP3/FLEXIO0_D7/ADC0_A15/CMP2_IN2, direction: INPUT, gpio_per_interrupt_sel: output0,
    gpio_per_interrupt: kGPIO_InterruptFallingEdge, slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable,
    invert_input: normal}
  - {pin_num: F10, peripheral: GPIO0, signal: 'GPIO, 26', pin_signal: PIO0_26/FC1_P2/CT0_MAT2/ADC0_B18, direction: INPUT, gpio_per_interrupt_sel: output1, gpio_per_interrupt: kGPIO_InterruptFallingEdge}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBUTTONsPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBUTTONsPins(void)
{
    /* Enables the clock for GPIO0: Enables clock */
    CLOCK_EnableClock(kCLOCK_Gpio0);
    /* Enables the clock for PORT0 controller: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port0);

    gpio_pin_config_t SW2_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO0_23 (pin B7)  */
    GPIO_PinInit(BOARD_INITBUTTONSPINS_SW2_GPIO, BOARD_INITBUTTONSPINS_SW2_PIN, &SW2_config);

    gpio_pin_config_t BUTTON_CLICK_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO0_26 (pin F10)  */
    GPIO_PinInit(BOARD_INITBUTTONSPINS_BUTTON_CLICK_GPIO, BOARD_INITBUTTONSPINS_BUTTON_CLICK_PIN, &BUTTON_CLICK_config);

    GPIO0->ICR[23] = ((GPIO0->ICR[23] &
                       /* Mask bits to zero which are setting */
                       (~(GPIO_ICR_IRQS_MASK | GPIO_ICR_ISF_MASK)))

                      /* Interrupt Select: Interrupt, trigger output, or DMA request 0. */
                      | GPIO_ICR_IRQS(ICR_IRQS_irqs0));

    /* Interrupt configuration on GPIO0_23 (pin B7): Interrupt on falling edge */
    GPIO_SetPinInterruptConfig(BOARD_INITBUTTONSPINS_SW2_GPIO, BOARD_INITBUTTONSPINS_SW2_PIN, kGPIO_InterruptFallingEdge);

    GPIO0->ICR[26] = ((GPIO0->ICR[26] &
                       /* Mask bits to zero which are setting */
                       (~(GPIO_ICR_IRQS_MASK | GPIO_ICR_ISF_MASK)))

                      /* Interrupt Select: Interrupt, trigger output, or DMA request 1. */
                      | GPIO_ICR_IRQS(ICR_IRQS_irqs1));

    /* Interrupt configuration on GPIO0_26 (pin F10): Interrupt on falling edge */
    GPIO_SetPinInterruptConfig(BOARD_INITBUTTONSPINS_BUTTON_CLICK_GPIO, BOARD_INITBUTTONSPINS_BUTTON_CLICK_PIN, kGPIO_InterruptFallingEdge);

    const port_pin_config_t SW2 = {/* Internal pull-up/down resistor is disabled */
                                   .pullSelect = kPORT_PullDisable,
                                   /* Low internal pull resistor value is selected. */
                                   .pullValueSelect = kPORT_LowPullResistor,
                                   /* Fast slew rate is configured */
                                   .slewRate = kPORT_FastSlewRate,
                                   /* Passive input filter is disabled */
                                   .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                   /* Open drain output is disabled */
                                   .openDrainEnable = kPORT_OpenDrainDisable,
                                   /* Low drive strength is configured */
                                   .driveStrength = kPORT_LowDriveStrength,
                                   /* Pin is configured as PIO0_23 */
                                   .mux = kPORT_MuxAlt0,
                                   /* Digital input enabled */
                                   .inputBuffer = kPORT_InputBufferEnable,
                                   /* Digital input is not inverted */
                                   .invertInput = kPORT_InputNormal,
                                   /* Pin Control Register fields [15:0] are not locked */
                                   .lockRegister = kPORT_UnlockRegister};
    /* PORT0_23 (pin B7) is configured as PIO0_23 */
    PORT_SetPinConfig(BOARD_INITBUTTONSPINS_SW2_PORT, BOARD_INITBUTTONSPINS_SW2_PIN, &SW2);

    /* PORT0_26 (pin F10) is configured as PIO0_26 */
    PORT_SetPinMux(BOARD_INITBUTTONSPINS_BUTTON_CLICK_PORT, BOARD_INITBUTTONSPINS_BUTTON_CLICK_PIN, kPORT_MuxAlt0);

    PORT0->PCR[26] = ((PORT0->PCR[26] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    const port_pin_config_t SW3 = {/* Internal pull-up resistor is enabled */
                                   .pullSelect = kPORT_PullUp,
                                   /* Low internal pull resistor value is selected. */
                                   .pullValueSelect = kPORT_LowPullResistor,
                                   /* Fast slew rate is configured */
                                   .slewRate = kPORT_FastSlewRate,
                                   /* Passive input filter is disabled */
                                   .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                   /* Open drain output is disabled */
                                   .openDrainEnable = kPORT_OpenDrainDisable,
                                   /* Low drive strength is configured */
                                   .driveStrength = kPORT_LowDriveStrength,
                                   /* Pin is configured as PIO0_6 */
                                   .mux = kPORT_MuxAlt0,
                                   /* Digital input enabled */
                                   .inputBuffer = kPORT_InputBufferEnable,
                                   /* Digital input is not inverted */
                                   .invertInput = kPORT_InputNormal,
                                   /* Pin Control Register fields [15:0] are not locked */
                                   .lockRegister = kPORT_UnlockRegister};
    /* PORT0_6 (pin C14) is configured as PIO0_6 */
    PORT_SetPinConfig(BOARD_INITBUTTONSPINS_SW3_PORT, BOARD_INITBUTTONSPINS_SW3_PIN, &SW3);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', prefix: BOARD_, coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: B12, peripheral: GPIO0, signal: 'GPIO, 10', pin_signal: PIO0_10/FC0_P6/CT0_MAT0/FLEXIO0_D2/ADC0_B10, slew_rate: fast, open_drain: disable, drive_strength: low,
    pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: L4, peripheral: QDC0, signal: 'PHASE, A', pin_signal: PIO1_22/TRIG_IN3/FC5_P6/FC4_P2/CT_INP14/SCT0_OUT4/FLEXIO0_D30/SMARTDMA_PIO18/ADC1_A22}
  - {pin_num: H2, peripheral: INPUTMUX0, signal: 'TRIG_IN, 5', pin_signal: PIO2_0/TRIG_IN5/FC9_P6/SDHC0_D5/SCT0_IN0/PWM1_A3/FLEXIO0_D8/SMARTDMA_PIO20/FLEXSPI0_B_SS1_b/SAI0_RX_BCLK}
  - {peripheral: QDC0, signal: 'PHASE, B', pin_signal: TRIG_IN5}
  - {pin_num: T1, peripheral: INPUTMUX0, signal: 'TRIG_IN, 6', pin_signal: PIO4_2/TRIG_IN6/FC2_P2/CT_INP12/SMARTDMA_PIO26/PLU_IN2/SINC0_MBIT3/DAC0_OUT/ADC0_A4/ADC1_A4/CMP0_IN4N/CMP1_IN4N/CMP2_IN4N}
  - {peripheral: QDC1, signal: 'PHASE, A', pin_signal: TRIG_IN6}
  - {pin_num: U1, peripheral: INPUTMUX0, signal: 'TRIG_IN, 7', pin_signal: PIO4_3/WUU0_IN19/TRIG_IN7/FC2_P3/CT_INP13/SMARTDMA_PIO27/PLU_IN3/DAC1_OUT/ADC0_B4/ADC1_B4/CMP0_IN5N/CMP1_IN5N/CMP2_IN5N}
  - {peripheral: QDC1, signal: 'PHASE, B', pin_signal: TRIG_IN7}
  - {pin_num: K2, peripheral: PWM1, signal: 'A, 0', pin_signal: PIO2_6/TRIG_IN4/FC9_P4/SDHC0_D3/SCT0_OUT4/PWM1_A0/FLEXIO0_D14/SMARTDMA_PIO26/FLEXSPI0_B_DATA2/SINC0_MCLK2/SAI0_TX_BCLK,
    direction: OUTPUT}
  - {pin_num: K3, peripheral: PWM1, signal: 'A, 1', pin_signal: PIO2_4/WUU0_IN17/FC9_P0/SDHC0_CLK/SCT0_OUT2/PWM1_A1/FLEXIO0_D12/SMARTDMA_PIO24/FLEXSPI0_B_DATA0/SINC0_MCLK1/SAI0_RXD1,
    direction: OUTPUT}
  - {pin_num: L5, peripheral: GPIO1, signal: 'GPIO, 21', pin_signal: PIO1_21/TRIG_OUT2/FC5_P5/FC4_P1/CT3_MAT3/SCT0_OUT9/FLEXIO0_D29/SMARTDMA_PIO17/PLU_OUT7/ENET0_MDIO/SAI1_MCLK/CAN1_RXD/ADC1_A21/CMP2_IN3,
    direction: OUTPUT}
  - {pin_num: M17, peripheral: GPIO3, signal: 'GPIO, 20', pin_signal: PIO3_20/WUU0_IN27/TRIG_OUT0/FC8_P4/FC6_P0/CT2_MAT2/PWM1_A3/FLEXIO0_D28/SMARTDMA_PIO20/SIM0_PD/SAI1_TXD0,
    direction: OUTPUT}
  - {pin_num: T7, peripheral: GPIO4, signal: 'GPIO, 13', pin_signal: PIO4_13/TRIG_IN8/FC2_P1/USB1_ID/CT4_MAT1/FLEXIO0_D21/PLU_OUT1/SINC0_MBIT0/CAN0_TXD/OPAMP0_INP1/ADC0_B5/ADC1_B5,
    direction: OUTPUT}
  - {pin_num: J15, peripheral: GPIO3, signal: 'GPIO, 16', pin_signal: PIO3_16/FC8_P2/CT_INP8/PWM1_A2/FLEXIO0_D24/SMARTDMA_PIO16/SIM0_CLK/SAI1_TX_BCLK, direction: OUTPUT}
  - {pin_num: P3, peripheral: ADC0, signal: 'A, 0', pin_signal: ADC0_A0}
  - {pin_num: R3, peripheral: ADC0, signal: 'B, 0', pin_signal: ADC0_B0}
  - {pin_num: E11, peripheral: CTIMER0, signal: 'CAPTURE, 0', pin_signal: PIO0_14/FC1_P6/FC0_P2/CT_INP2/UTICK_CAP0/FLEXIO0_D6/ADC0_B14, identifier: RC_1_RISE}
  - {pin_num: G13, peripheral: CTIMER0, signal: 'CAPTURE, 1', pin_signal: PIO0_15/FC0_P3/CT_INP3/UTICK_CAP1/FLEXIO0_D7/ADC0_B15, identifier: RC_2_RISE}
  - {pin_num: E11, peripheral: CTIMER0, signal: 'CAPTURE, 2', pin_signal: PIO0_14/FC1_P6/FC0_P2/CT_INP2/UTICK_CAP0/FLEXIO0_D6/ADC0_B14, identifier: RC_1_FALL}
  - {pin_num: G13, peripheral: CTIMER0, signal: 'CAPTURE, 3', pin_signal: PIO0_15/FC0_P3/CT_INP3/UTICK_CAP1/FLEXIO0_D7/ADC0_B15, identifier: RC_2_FALL}
  - {peripheral: ADC0, signal: 'TRG_CH, 0', pin_signal: PWM1_A0_TRIG0}
  - {pin_num: K17, peripheral: CTIMER2, signal: 'MATCH, 1', pin_signal: PIO3_19/FC7_P6/CT2_MAT1/PWM1_X1/FLEXIO0_D27/SMARTDMA_PIO19/SAI1_RX_FS}
  - {pin_num: P2, peripheral: LP_FLEXCOMM2, signal: LPFLEXCOMM_P1, pin_signal: PIO4_1/TRIG_IN7/FC2_P1/CT_INP17/SMARTDMA_PIO25/PLU_IN1, identifier: PIXY_SCK}
  - {pin_num: P1, peripheral: LP_FLEXCOMM2, signal: LPFLEXCOMM_P0, pin_signal: PIO4_0/WUU0_IN18/TRIG_IN6/FC2_P0/CT_INP16/SMARTDMA_PIO24/PLU_IN0/SINC0_MCLK3, identifier: PIXY_SDA}
  - {pin_num: M12, peripheral: ADC1, signal: 'B, 12', pin_signal: PIO5_4/TRIG_OUT7/SPC_LPREQ/TAMPER2/ADC1_B12}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Enables the clock for GPIO1: Enables clock */
    CLOCK_EnableClock(kCLOCK_Gpio1);
    /* Enables the clock for GPIO3: Enables clock */
    CLOCK_EnableClock(kCLOCK_Gpio3);
    /* Enables the clock for GPIO4: Enables clock */
    CLOCK_EnableClock(kCLOCK_Gpio4);
    /* Enables the clock for INPUTMUX: Enables clock */
    CLOCK_EnableClock(kCLOCK_InputMux0);
    /* Enables the clock for PORT0 controller: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port0);
    /* Enables the clock for PORT1: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port1);
    /* Enables the clock for PORT2: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port2);
    /* Enables the clock for PORT3: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port3);
    /* Enables the clock for PORT4: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port4);

    gpio_pin_config_t M1_INA_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_21 (pin L5)  */
    GPIO_PinInit(BOARD_M1_INA_GPIO, BOARD_M1_INA_PIN, &M1_INA_config);

    gpio_pin_config_t M2_INB_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_16 (pin J15)  */
    GPIO_PinInit(BOARD_M2_INB_GPIO, BOARD_M2_INB_PIN, &M2_INB_config);

    gpio_pin_config_t M1_INB_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_20 (pin M17)  */
    GPIO_PinInit(BOARD_M1_INB_GPIO, BOARD_M1_INB_PIN, &M1_INB_config);

    gpio_pin_config_t M2_INA_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO4_13 (pin T7)  */
    GPIO_PinInit(BOARD_M2_INA_GPIO, BOARD_M2_INA_PIN, &M2_INA_config);
    /* PWM1_A0_TRIG0 is selected as trigger input for ADC0 channel 0 */
    INPUTMUX_AttachSignal(INPUTMUX0, 0U, kINPUTMUX_Pwm1A0Trig0ToAdc0Trigger);
    /* Ctimer input 2 is selected for TIMER0 CAPTSEL 0 */
    INPUTMUX_AttachSignal(INPUTMUX0, 0U, kINPUTMUX_CtimerInp2ToTimer0Captsel);
    /* Ctimer input 3 is selected for TIMER0 CAPTSEL 1 */
    INPUTMUX_AttachSignal(INPUTMUX0, 1U, kINPUTMUX_CtimerInp3ToTimer0Captsel);
    /* Ctimer input 2 is selected for TIMER0 CAPTSEL 2 */
    INPUTMUX_AttachSignal(INPUTMUX0, 2U, kINPUTMUX_CtimerInp2ToTimer0Captsel);
    /* Ctimer input 3 is selected for TIMER0 CAPTSEL 3 */
    INPUTMUX_AttachSignal(INPUTMUX0, 3U, kINPUTMUX_CtimerInp3ToTimer0Captsel);
    /* PIO1_22 is selected for PINT input 0 */
    INPUTMUX_AttachSignal(INPUTMUX0, 0U, kINPUTMUX_GpioPort1Pin22ToPintsel);
    /* Pin interrupt 0 is selected as trigger input for QDC0 PHASEA channel 0 */
    INPUTMUX_AttachSignal(INPUTMUX0, 0U, kINPUTMUX_PinInt0ToQdc0Phasea);
    /* TRIG_IN5 is selected as trigger input for QDC0 PHASEB channel 0 */
    INPUTMUX_AttachSignal(INPUTMUX0, 0U, kINPUTMUX_TrigIn5ToQdc0Phaseb);
    /* TRIG_IN6 is selected as trigger input for QDC1 PHASEA channel 0 */
    INPUTMUX_AttachSignal(INPUTMUX0, 0U, kINPUTMUX_TrigIn6ToQdc1Phasea);
    /* TRIG_IN7 is selected as trigger input for QDC1 PHASEB channel 0 */
    INPUTMUX_AttachSignal(INPUTMUX0, 0U, kINPUTMUX_TrigIn7ToQdc1Phaseb);

    const port_pin_config_t LED_RED = {/* Internal pull-up/down resistor is disabled */
                                       .pullSelect = kPORT_PullDisable,
                                       /* Low internal pull resistor value is selected. */
                                       .pullValueSelect = kPORT_LowPullResistor,
                                       /* Fast slew rate is configured */
                                       .slewRate = kPORT_FastSlewRate,
                                       /* Passive input filter is disabled */
                                       .passiveFilterEnable = kPORT_PassiveFilterDisable,
                                       /* Open drain output is disabled */
                                       .openDrainEnable = kPORT_OpenDrainDisable,
                                       /* Low drive strength is configured */
                                       .driveStrength = kPORT_LowDriveStrength,
                                       /* Pin is configured as PIO0_10 */
                                       .mux = kPORT_MuxAlt0,
                                       /* Digital input enabled */
                                       .inputBuffer = kPORT_InputBufferEnable,
                                       /* Digital input is not inverted */
                                       .invertInput = kPORT_InputNormal,
                                       /* Pin Control Register fields [15:0] are not locked */
                                       .lockRegister = kPORT_UnlockRegister};
    /* PORT0_10 (pin B12) is configured as PIO0_10 */
    PORT_SetPinConfig(BOARD_LED_RED_PORT, BOARD_LED_RED_PIN, &LED_RED);

    /* PORT0_14 (pin E11) is configured as CT_INP2 */
    PORT_SetPinMux(BOARD_RC_1_RISE_PORT, BOARD_RC_1_RISE_PIN, kPORT_MuxAlt4);

    PORT0->PCR[14] = ((PORT0->PCR[14] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_15 (pin G13) is configured as CT_INP3 */
    PORT_SetPinMux(BOARD_RC_2_RISE_PORT, BOARD_RC_2_RISE_PIN, kPORT_MuxAlt4);

    PORT0->PCR[15] = ((PORT0->PCR[15] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_21 (pin L5) is configured as PIO1_21 */
    PORT_SetPinMux(BOARD_M1_INA_PORT, BOARD_M1_INA_PIN, kPORT_MuxAlt0);

    PORT1->PCR[21] = ((PORT1->PCR[21] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_22 (pin L4) is configured as PIO1_22 */
    PORT_SetPinMux(PORT1, 22U, kPORT_MuxAlt0);

    PORT1->PCR[22] = ((PORT1->PCR[22] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT2_0 (pin H2) is configured as TRIG_IN5 */
    PORT_SetPinMux(PORT2, 0U, kPORT_MuxAlt1);

    PORT2->PCR[0] = ((PORT2->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT2_4 (pin K3) is configured as PWM1_A1 */
    PORT_SetPinMux(BOARD_M2_PWM_PORT, BOARD_M2_PWM_PIN, kPORT_MuxAlt5);

    PORT2->PCR[4] = ((PORT2->PCR[4] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT2_6 (pin K2) is configured as PWM1_A0 */
    PORT_SetPinMux(BOARD_M1_PWM_PORT, BOARD_M1_PWM_PIN, kPORT_MuxAlt5);

    PORT2->PCR[6] = ((PORT2->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_16 (pin J15) is configured as PIO3_16 */
    PORT_SetPinMux(BOARD_M2_INB_PORT, BOARD_M2_INB_PIN, kPORT_MuxAlt0);

    PORT3->PCR[16] = ((PORT3->PCR[16] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_19 (pin K17) is configured as CT2_MAT1 */
    PORT_SetPinMux(BOARD_SERVO_PORT, BOARD_SERVO_PIN, kPORT_MuxAlt4);

    PORT3->PCR[19] = ((PORT3->PCR[19] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_20 (pin M17) is configured as PIO3_20 */
    PORT_SetPinMux(BOARD_M1_INB_PORT, BOARD_M1_INB_PIN, kPORT_MuxAlt0);

    PORT3->PCR[20] = ((PORT3->PCR[20] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT4_0 (pin P1) is configured as FC2_P0 */
    PORT_SetPinMux(BOARD_PIXY_SDA_PORT, BOARD_PIXY_SDA_PIN, kPORT_MuxAlt2);

    PORT4->PCR[0] = ((PORT4->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT4_1 (pin P2) is configured as FC2_P1 */
    PORT_SetPinMux(BOARD_PIXY_SCK_PORT, BOARD_PIXY_SCK_PIN, kPORT_MuxAlt2);

    PORT4->PCR[1] = ((PORT4->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT4_13 (pin T7) is configured as PIO4_13 */
    PORT_SetPinMux(BOARD_M2_INA_PORT, BOARD_M2_INA_PIN, kPORT_MuxAlt0);

    PORT4->PCR[13] = ((PORT4->PCR[13] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT4_2 (pin T1) is configured as TRIG_IN6 */
    PORT_SetPinMux(PORT4, 2U, kPORT_MuxAlt1);

    PORT4->PCR[2] = ((PORT4->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT4_3 (pin U1) is configured as TRIG_IN7 */
    PORT_SetPinMux(PORT4, 3U, kPORT_MuxAlt1);

    PORT4->PCR[3] = ((PORT4->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT5->PCR[4] = ((PORT5->PCR[4] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT5_4 (pin M12) is configured as ADC1_B12. */
                     | PORT_PCR_MUX(PORT5_PCR_MUX_mux00)

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
